Fix MinGW unicode compilation bug
This fixes the unicode bug that causes mingw compilation to fail on by
adding the the extra unicode definitions for MinGW similar to how they
are added for MSVC. This seems to make clFFT
compatible with Mingw.

fft_binary_lookup.cpp: In member function 'bool
FFTBinaryLookup::CacheEntry::exclusive_create()':
fft_binary_lookup.cpp:129:36: error: cannot convert 'const wchar_t*' to
'LPCSTR {aka const char*}' for argument '1' to 'void*
CreateFileA(LPCSTR, DWORD, DWORD, LPSECURITY_ATTRIBUTES, DWORD, DWORD,
HANDLE)'
NULL);

Short test log:

https://gist.github.com/polyZealous/88719c00e5fd4518a9135f64b4c78c90#file-mingw_clfft_test_log-txt